packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  esbuild: true

catalog:
  "@fontsource/nunito-sans": ^5.2.7
  "@storybook/addon-a11y": ^10.4.6
  "@storybook/addon-vitest": ^10.4.6
  "@types/node": ^24
  chromatic: ^17.5.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: 4.1.9

catalogMode: prefer

minimumReleaseAgeExclude:
  - "@tybys/wasm-util@0.10.3"
  - "@typescript-eslint/project-service@8.62.0"
  - "@typescript-eslint/scope-manager@8.62.0"
  - "@typescript-eslint/tsconfig-utils@8.62.0"
  - "@typescript-eslint/types@8.62.0"
  - "@typescript-eslint/typescript-estree@8.62.0"
  - "@typescript-eslint/utils@8.62.0"
  - "@typescript-eslint/visitor-keys@8.62.0"
  - electron-to-chromium@1.5.377
  - vite@8.1.0

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

trustLockfile: true
