import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.resolve(__dirname, "../src");
const outputPath = path.resolve(srcDir, "tokens.theme.css");

const SOURCE_FILES = ["tokens.generated.css", "tokens.web.css"];

const DIRECT_PREFIXES = ["color-", "spacing-", "radius-", "border-width-", "font-weight-"];

const TRANSFORM_PREFIXES = {
  "font-family-": "font-",
  "font-size-": "text-",
  "line-height-": "leading-",
  "letter-spacing-": "tracking-",
};

function extractVariableNames(content) {
  const names = new Set();
  const pattern = /--([a-z0-9-]+)\s*:/g;

  for (const match of content.matchAll(pattern)) {
    names.add(match[1]);
  }

  return names;
}

function toThemeEntry(name) {
  for (const prefix of DIRECT_PREFIXES) {
    if (name.startsWith(prefix)) {
      return `  --${name}: var(--${name});`;
    }
  }

  for (const [sourcePrefix, targetPrefix] of Object.entries(TRANSFORM_PREFIXES)) {
    if (name.startsWith(sourcePrefix)) {
      const suffix = name.slice(sourcePrefix.length);
      return `  --${targetPrefix}${suffix}: var(--${name});`;
    }
  }

  return null;
}

function generateThemeCss(variableNames) {
  const entries = [...variableNames]
    .sort((left, right) => left.localeCompare(right))
    .map(toThemeEntry)
    .filter((entry) => entry !== null);

  return [
    "/**",
    " * Tailwind v4 theme bridge for DS-12 design tokens.",
    " * Generated by scripts/generate-theme.mjs — do not edit directly.",
    " *",
    " * Import after tokens.css:",
    ' *   @import "@ds-12/design-tokens/tokens.css";',
    ' *   @import "@ds-12/design-tokens/theme.css";',
    " */",
    "",
    "@theme inline {",
    ...entries,
    "}",
    "",
  ].join("\n");
}

const variableNames = new Set();

for (const fileName of SOURCE_FILES) {
  const filePath = path.resolve(srcDir, fileName);
  const content = fs.readFileSync(filePath, "utf8");

  for (const name of extractVariableNames(content)) {
    variableNames.add(name);
  }
}

const themeCss = generateThemeCss(variableNames);
fs.writeFileSync(outputPath, themeCss, "utf8");

console.log(`Wrote ${outputPath} (${themeCss.split("\n").length - 1} lines)`);
